[I 16:55:51.261 LabApp] JupyterLab extension loaded from /Users/jacobyeung/anaconda3/lib/python3.8/site-packages/jupyterlab
[I 16:55:51.262 LabApp] JupyterLab application directory is /Users/jacobyeung/anaconda3/share/jupyter/lab
[I 16:55:51.266 LabApp] Serving notebooks from local directory: /Users/jacobyeung/Berkeley/Spring 2021/CS 182/CS-182-Project
[I 16:55:51.266 LabApp] The Jupyter Notebook is running at:
[I 16:55:51.266 LabApp] http://localhost:8890/?token=d842084f935286e6d11ec68fd23a49f6269e4d099c66cbc3
[I 16:55:51.266 LabApp]  or http://127.0.0.1:8890/?token=d842084f935286e6d11ec68fd23a49f6269e4d099c66cbc3
[I 16:55:51.266 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:55:51.287 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jacobyeung/Library/Jupyter/runtime/nbserver-12192-open.html
    Or copy and paste one of these URLs:
        http://localhost:8890/?token=d842084f935286e6d11ec68fd23a49f6269e4d099c66cbc3
     or http://127.0.0.1:8890/?token=d842084f935286e6d11ec68fd23a49f6269e4d099c66cbc3
[I 16:55:55.085 LabApp] Build is up to date
[W 16:55:55.595 LabApp] 404 GET /api/contents/StyleTransfer.ipynb?content=0&1616975755575 (127.0.0.1): No such file or directory: StyleTransfer.ipynb
[W 16:55:55.595 LabApp] No such file or directory: StyleTransfer.ipynb
[W 16:55:55.596 LabApp] 404 GET /api/contents/StyleTransfer.ipynb?content=0&1616975755575 (127.0.0.1) 3.75ms referer=http://localhost:8890/lab
[W 16:55:55.599 LabApp] 404 GET /api/contents/LSTM_Captioning.ipynb?content=0&1616975755575 (127.0.0.1): No such file or directory: LSTM_Captioning.ipynb
[W 16:55:55.599 LabApp] No such file or directory: LSTM_Captioning.ipynb
[W 16:55:55.599 LabApp] 404 GET /api/contents/LSTM_Captioning.ipynb?content=0&1616975755575 (127.0.0.1) 3.06ms referer=http://localhost:8890/lab
[W 16:55:55.599 LabApp] 404 GET /api/contents/lstm_pytorch.ipynb?content=0&1616975755575 (127.0.0.1): No such file or directory: lstm_pytorch.ipynb
[W 16:55:55.599 LabApp] No such file or directory: lstm_pytorch.ipynb
[W 16:55:55.600 LabApp] 404 GET /api/contents/lstm_pytorch.ipynb?content=0&1616975755575 (127.0.0.1) 3.15ms referer=http://localhost:8890/lab
[W 16:55:55.603 LabApp] 404 GET /api/contents/deeplearning/style_transfer.py?content=0&1616975755576 (127.0.0.1): No such file or directory: deeplearning/style_transfer.py
[W 16:55:55.604 LabApp] No such file or directory: deeplearning/style_transfer.py
[W 16:55:55.604 LabApp] 404 GET /api/contents/deeplearning/style_transfer.py?content=0&1616975755576 (127.0.0.1) 5.75ms referer=http://localhost:8890/lab
[W 16:55:55.605 LabApp] 404 GET /api/contents/deeplearning/rnn_layers.py?content=0&1616975755576 (127.0.0.1): No such file or directory: deeplearning/rnn_layers.py
[W 16:55:55.605 LabApp] No such file or directory: deeplearning/rnn_layers.py
[W 16:55:55.606 LabApp] 404 GET /api/contents/deeplearning/rnn_layers.py?content=0&1616975755576 (127.0.0.1) 1.15ms referer=http://localhost:8890/lab
[W 16:55:55.607 LabApp] 404 GET /api/contents/deeplearning/captioning_solver.py?content=0&1616975755576 (127.0.0.1): No such file or directory: deeplearning/captioning_solver.py
[W 16:55:55.607 LabApp] No such file or directory: deeplearning/captioning_solver.py
[W 16:55:55.607 LabApp] 404 GET /api/contents/deeplearning/captioning_solver.py?content=0&1616975755576 (127.0.0.1) 1.47ms referer=http://localhost:8890/lab
TermSocket.open: 1
[I 16:55:55.667 LabApp] New terminal with specified name: 1
TermSocket.open: Opened 1
[I 17:00:38.226 LabApp] Creating new notebook in /
[I 17:00:38.493 LabApp] Kernel started: cf22b87e-98dd-4d54-af5a-ab5d751a8cfe
[I 17:00:39.445 LabApp] Starting buffering for cf22b87e-98dd-4d54-af5a-ab5d751a8cfe:447b240f-8080-465f-be98-d0600afa8b25
[I 17:02:38.708 LabApp] Saving file at /Untitled.ipynb
[I 17:06:38.752 LabApp] Saving file at /Untitled.ipynb
[I 17:08:38.787 LabApp] Saving file at /Untitled.ipynb
[I 17:10:38.818 LabApp] Saving file at /Untitled.ipynb
[I 17:12:38.856 LabApp] Saving file at /Untitled.ipynb
[I 17:13:02.503 LabApp] Saving file at /Untitled.ipynb
[I 23:06:34.258 LabApp] interrupted
Serving notebooks from local directory: /Users/jacobyeung/Berkeley/Spring 2021/CS 182/CS-182-Project
1 active kernel
The Jupyter Notebook is running at:
http://localhost:8890/?token=d842084f935286e6d11ec68fd23a49f6269e4d099c66cbc3
 or http://127.0.0.1:8890/?token=d842084f935286e6d11ec68fd23a49f6269e4d099c66cbc3
Shutdown this notebook server (y/[n])? [C 23:06:36.292 LabApp] received signal 2, stopping
[I 23:06:36.298 LabApp] Shutting down 1 kernel
[I 23:06:36.813 LabApp] Kernel shutdown: cf22b87e-98dd-4d54-af5a-ab5d751a8cfe
Traceback (most recent call last):
  File "/Users/jacobyeung/anaconda3/lib/python3.8/site-packages/traitlets/config/loader.py", line 254, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'nbserver_extensions'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jacobyeung/anaconda3/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
  File "/Users/jacobyeung/anaconda3/lib/python3.8/site-packages/jupyter_core/application.py", line 270, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/Users/jacobyeung/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<decorator-gen-7>", line 2, in initialize
  File "/Users/jacobyeung/anaconda3/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "/Users/jacobyeung/anaconda3/lib/python3.8/site-packages/notebook/notebookapp.py", line 1767, in initialize
    self.init_server_extension_config()
  File "/Users/jacobyeung/anaconda3/lib/python3.8/site-packages/notebook/notebookapp.py", line 1654, in init_server_extension_config
    self.config.NotebookApp.nbserver_extensions.update({modulename: enabled})
  File "/Users/jacobyeung/anaconda3/lib/python3.8/site-packages/traitlets/config/loader.py", line 279, in __getattr__
    return self.__getitem__(key)
  File "/Users/jacobyeung/anaconda3/lib/python3.8/site-packages/traitlets/config/loader.py", line 262, in __getitem__
    v = LazyConfigValue()
  File "/Users/jacobyeung/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py", line 958, in __new__
    inst.setup_instance(*args, **kwargs)
  File "/Users/jacobyeung/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py", line 982, in setup_instance
    def setup_instance(self, *args, **kwargs):
KeyboardInterrupt
[I 13:33:53.869 LabApp] JupyterLab extension loaded from /Users/jacobyeung/anaconda3/lib/python3.8/site-packages/jupyterlab
[I 13:33:53.889 LabApp] JupyterLab application directory is /Users/jacobyeung/anaconda3/share/jupyter/lab
[I 13:33:53.893 LabApp] Serving notebooks from local directory: /Users/jacobyeung/Berkeley/Spring 2021/CS 182/CS-182-Project
[I 13:33:53.893 LabApp] The Jupyter Notebook is running at:
[I 13:33:53.893 LabApp] http://localhost:8890/?token=ea7d546bea01b41f9cf75e5e822fdcc87e739eda5f816246
[I 13:33:53.893 LabApp]  or http://127.0.0.1:8890/?token=ea7d546bea01b41f9cf75e5e822fdcc87e739eda5f816246
[I 13:33:53.893 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:33:53.950 LabApp] 
    
    To access the notebook, open this file in a browser:
        file:///Users/jacobyeung/Library/Jupyter/runtime/nbserver-92884-open.html
    Or copy and paste one of these URLs:
        http://localhost:8890/?token=ea7d546bea01b41f9cf75e5e822fdcc87e739eda5f816246
     or http://127.0.0.1:8890/?token=ea7d546bea01b41f9cf75e5e822fdcc87e739eda5f816246
[I 13:33:58.675 LabApp] Build is up to date
[W 13:33:59.519 LabApp] Notebook timer.ipynb is not trusted
[W 13:33:59.575 LabApp] Notebook validation.ipynb is not trusted
[I 13:34:00.174 LabApp] Kernel started: 589d02ec-fa8c-466a-9a4c-1d706251e037
[I 13:34:00.187 LabApp] Kernel started: 993b95e5-dffd-432e-bed8-491bad038c20
[I 13:34:01.026 LabApp] Starting buffering for 993b95e5-dffd-432e-bed8-491bad038c20:759af332-66fb-4c69-bcd8-636efbd4925f
[I 13:34:24.476 LabApp] Creating new notebook in /
[I 13:34:24.705 LabApp] Kernel started: d01f93a2-7419-42ee-9e91-1c5736ff69f6
[I 13:36:00.070 LabApp] Saving file at /validation.ipynb
[W 13:36:00.071 LabApp] Notebook validation.ipynb is not trusted
[I 13:36:24.663 LabApp] Saving file at /Untitled.ipynb
[I 13:38:24.702 LabApp] Saving file at /val_creator.ipynb
[I 13:40:24.731 LabApp] Saving file at /val_creator.ipynb
[I 13:42:24.851 LabApp] Saving file at /val_creator.ipynb
[I 13:44:24.882 LabApp] Saving file at /val_creator.ipynb
[I 13:46:24.913 LabApp] Saving file at /val_creator.ipynb
[I 13:46:48.798 LabApp] Saving file at /val_creator.ipynb
[I 13:47:00.968 LabApp] interrupted
Serving notebooks from local directory: /Users/jacobyeung/Berkeley/Spring 2021/CS 182/CS-182-Project
3 active kernels
The Jupyter Notebook is running at:
http://localhost:8890/?token=ea7d546bea01b41f9cf75e5e822fdcc87e739eda5f816246
 or http://127.0.0.1:8890/?token=ea7d546bea01b41f9cf75e5e822fdcc87e739eda5f816246
Shutdown this notebook server (y/[n])? [C 13:47:03.358 LabApp] received signal 2, stopping
[I 13:47:03.361 LabApp] Shutting down 3 kernels
[C 13:47:03.571 LabApp] received signal 2, stopping
[I 13:47:03.673 LabApp] Kernel shutdown: 589d02ec-fa8c-466a-9a4c-1d706251e037
[I 13:47:03.675 LabApp] Kernel shutdown: 993b95e5-dffd-432e-bed8-491bad038c20
[I 13:47:03.676 LabApp] Kernel shutdown: d01f93a2-7419-42ee-9e91-1c5736ff69f6
